### PR TITLE
Add GitHub workflow with fmt, clippy and unit tests

### PR DESCRIPTION
**Pull request by russell-islam**
Signed-off-by: Muminul Islam <muislam@microsoft.com>

### CODE REVIEW

**Comment by liuw** [comment]
I don't have a lot of experience with GitHub action, nor do I know how it is configured here.

I would like you to fix the commit subject line to `Add GitHub workflow with fmt, clippy and unit tests`.

**Review by sameo — APPROVED** [review]

**Comment by sameo** [comment]
@liuw Are you ok with the commit subject line?

**Comment by liuw** [comment]
> 
> 
> @liuw Are you ok with the commit subject line?

The commit subject should be changed as I suggested. "git workflow" means completely different thing.

**Comment by russell-islam** [comment]
> > @liuw Are you ok with the commit subject line?
> 
> The commit subject should be changed as I suggested. "git workflow" means completely different thing.

Sorry. I missed it. Goingto chnage it.

**Comment by russell-islam** [comment]
Done. :)

**Review by liuw — APPROVED** [review]

**Pull request merged**
